# Generated by Django 4.2.5 on 2024-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('email', models.CharField(max_length=130)),
                ('subject', models.CharField(max_length=130)),
                ('mess', models.CharField(max_length=130)),
                ('date', models.DateField()),
            ],
        ),
    ]
